[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NEXT_PUBLIC_CHAIN_ID = "1"
  # Add other NEXT_PUBLIC_* environment variables on Netlify web UI, do NOT store private keys here.
